// Native binary loader - tries platform-specific packages, falls back to local .node file.
//
// In production: the correct @llamaindex/liteparse-<platform> optional dependency
// provides the .node binary. During development: `napi build` places it alongside package.json.

import { createRequire } from "node:module";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));

interface NativeBindings {
  LiteParse: new (config?: LiteParseNativeConfig) => LiteParseNative;
}

export interface LiteParseNativeConfig {
  ocrLanguage?: string;
  ocrEnabled?: boolean;
  ocrServerUrl?: string;
  tessdataPath?: string;
  maxPages?: number;
  targetPages?: string;
  dpi?: number;
  outputFormat?: string;
  preserveVerySmallText?: boolean;
  password?: string;
  quiet?: boolean;
}

export interface NativeTextItem {
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
  fontName?: string;
  fontSize?: number;
  confidence?: number;
}

export interface NativeParsedPage {
  pageNum: number;
  width: number;
  height: number;
  text: string;
  textItems: NativeTextItem[];
}

export interface NativeParseResult {
  pages: NativeParsedPage[];
  text: string;
}

export interface NativeScreenshotResult {
  pageNum: number;
  width: number;
  height: number;
  imageBuffer: Buffer;
}

export interface LiteParseNative {
  parse(input: string | Buffer): Promise<NativeParseResult>;
  screenshot(
    input: string,
    pageNumbers?: number[] | null,
  ): NativeScreenshotResult[];
  format(result: NativeParseResult): string;
  readonly config: LiteParseNativeConfig;
}

function loadNative(): NativeBindings {
  // Platform-specific package names generated by napi-rs
  const triples: Record<string, string> = {
    "darwin-x64": "@llamaindex/liteparse-darwin-x64",
    "darwin-arm64": "@llamaindex/liteparse-darwin-arm64",
    "linux-x64-gnu": "@llamaindex/liteparse-linux-x64-gnu",
    "linux-x64-musl": "@llamaindex/liteparse-linux-x64-musl",
    "linux-arm64-gnu": "@llamaindex/liteparse-linux-arm64-gnu",
    "linux-arm64-musl": "@llamaindex/liteparse-linux-arm64-musl",
    "win32-x64-msvc": "@llamaindex/liteparse-win32-x64-msvc",
  };

  // Try platform-specific package first
  const platform = process.platform;
  const arch = process.arch;

  const candidates: string[] = [];
  if (platform === "linux") {
    // Try gnu first, then musl
    candidates.push(`${platform}-${arch}-gnu`);
    candidates.push(`${platform}-${arch}-musl`);
  } else if (platform === "win32") {
    candidates.push(`${platform}-${arch}-msvc`);
  } else {
    candidates.push(`${platform}-${arch}`);
  }

  for (const key of candidates) {
    const pkg = triples[key];
    if (pkg) {
      try {
        return require(pkg);
      } catch {
        // Not installed, try next
      }
    }
  }

  // Fallback: local .node file (development builds)
  // Try several paths since __dirname may be dist/ or dist/src/
  const searchDirs = [__dirname, join(__dirname, ".."), join(__dirname, "..", "..")];
  // Try full triple names (e.g. liteparse.linux-x64-gnu.node) and simple name
  const fileNames = [
    ...candidates.map((c) => `liteparse.${c}.node`),
    `liteparse.${platform}-${arch}.node`,
    "liteparse.node",
  ];
  for (const dir of searchDirs) {
    for (const fileName of fileNames) {
      try {
        return require(join(dir, fileName));
      } catch {
        // try next
      }
    }
  }

  throw new Error(
    `Failed to load native module for ${platform}-${arch}. ` +
      `Ensure the correct optional dependency is installed.`,
  );
}

export const native = loadNative();
